            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">Home</a></li>
                <?php
                /*
                 * This script automatically gets the path of the site and shows the breadcrumbs (the path to the page) at the top of each subsite
                 * The name is automatically generated by taking the url and making the words uppercase
                 * If a custom name is needed, just add a text file called 'name.txt' to the directory containing just the name
                 */

                // get browser url after the domain (the directory), split it up, and remove empty array elements
                $path = array_filter(explode("/", explode('?', $_SERVER['REQUEST_URI'])[0]));
                $lastItem = end($path);
                $currentUrl = "/";
                foreach($path as $dir) {
                    $currentUrl .= $dir."/";
                    //echo $_SERVER["DOCUMENT_ROOT"].$currentUrl;
                    $name = ucwords(str_replace("-", " ", $dir));
                    //echo $name;
                    if(file_exists($_SERVER["DOCUMENT_ROOT"].$currentUrl."name.txt")) {
                        $name = trim(file_get_contents($_SERVER["DOCUMENT_ROOT"].$currentUrl."name.txt"));
                    }
                    if($lastItem == $dir) {
                        echo '<li class="breadcrumb-item active" aria-current="page">'.$name.'</li>';
                    } else {
                        echo '<li class="breadcrumb-item"><a href="'.$currentUrl.'">'.$name.'</a></li>';
                    }
                }
                ?>
            </ol>